#image: docker:18.09.7-dind

variables:
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  KUBERNETES_SERVICE_MEMORY_REQUEST: 12Gi

stages:
  - bump-and-publish

#.default_rules:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

bump-and-publish:
#  rules:
#    - !reference [ .default_rules, rules ]
  image: python:3.9
  timeout: 30m
  stage: bump-and-publish
  before_script:
    - python -m pip install twine
    - python -m pip install bumpversion
    - apt update && apt install -y git
    - echo "$PYPIRC" >> ~/.pypirc
  script:
    - echo "Bumping Python Elemeno SDK to version $CI_COMMIT_TAG"
    - git config --global user.email "hoffmann@elemeno.ai"
    - git config --global user.name "Hoffmann"
    - make version=$CI_COMMIT_TAG bump
    - cat setup.py
    - make pip-pypi-elemeno
  only:
    - tags
